name: Backend CI

# Define qué eventos disparan este pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Descarga el código del repositorio en la máquina virtual de GitHub
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Configura el entorno de Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' 
        cache: 'npm'       # Optimiza el tiempo de instalación guardando en caché node_modules

    # 3. Instala las dependencias de forma exacta y limpia (npm ci es más rápido que npm install)
    - name: Install dependencies
      run: npm ci

    # 4. Ejecuta el linter para asegurar que el código cumple las reglas de formato (comillas, espacios, etc.)
    - name: Run Linter
      run: npm run lint

    # 5. Intenta compilar el proyecto NestJS. Si hay errores de TypeScript, el pipeline fallará aquí.
    - name: Run Build
      run: npm run build